INSERT INTO "languages" (id, code, name) VALUES
  (gen_random_uuid(), 'en', 'English'),
  (gen_random_uuid(), 'es', 'Spanish'),
  (gen_random_uuid(), 'fr', 'French'),
  (gen_random_uuid(), 'de', 'German'),
  (gen_random_uuid(), 'pt', 'Portuguese'),
  (gen_random_uuid(), 'it', 'Italian'),
  (gen_random_uuid(), 'nl', 'Dutch'),
  (gen_random_uuid(), 'ru', 'Russian'),
  (gen_random_uuid(), 'zh', 'Mandarin Chinese'),
  (gen_random_uuid(), 'ja', 'Japanese'),
  (gen_random_uuid(), 'ko', 'Korean'),
  (gen_random_uuid(), 'ar', 'Arabic'),
  (gen_random_uuid(), 'hi', 'Hindi'),
  (gen_random_uuid(), 'bn', 'Bengali'),
  (gen_random_uuid(), 'sw', 'Swahili'),
  (gen_random_uuid(), 'am', 'Amharic'),
  (gen_random_uuid(), 'ha', 'Hausa'),
  (gen_random_uuid(), 'yo', 'Yoruba'),
  (gen_random_uuid(), 'zu', 'Zulu'),
  (gen_random_uuid(), 'tr', 'Turkish');