INSERT INTO "skills" (id, name, category, "createdAt") VALUES
  (gen_random_uuid(), 'Python', 'Programming', NOW()),
  (gen_random_uuid(), 'JavaScript', 'Programming', NOW()),
  (gen_random_uuid(), 'TypeScript', 'Programming', NOW()),
  (gen_random_uuid(), 'Java', 'Programming', NOW()),
  (gen_random_uuid(), 'C++', 'Programming', NOW()),
  (gen_random_uuid(), 'C#', 'Programming', NOW()),
  (gen_random_uuid(), 'Go', 'Programming', NOW()),
  (gen_random_uuid(), 'Rust', 'Programming', NOW()),
  (gen_random_uuid(), 'Ruby', 'Programming', NOW()),
  (gen_random_uuid(), 'PHP', 'Programming', NOW()),
  (gen_random_uuid(), 'Swift', 'Programming', NOW()),
  (gen_random_uuid(), 'Kotlin', 'Programming', NOW()),
  (gen_random_uuid(), 'SQL', 'Data', NOW()),
  (gen_random_uuid(), 'PostgreSQL', 'Data', NOW()),
  (gen_random_uuid(), 'MySQL', 'Data', NOW()),
  (gen_random_uuid(), 'MongoDB', 'Data', NOW()),
  (gen_random_uuid(), 'Data Analysis', 'Data', NOW()),
  (gen_random_uuid(), 'Data Visualization', 'Data', NOW()),
  (gen_random_uuid(), 'Excel', 'Data', NOW()),
  (gen_random_uuid(), 'Statistics', 'Data', NOW()),
  (gen_random_uuid(), 'Machine Learning', 'AI/ML', NOW()),
  (gen_random_uuid(), 'Deep Learning', 'AI/ML', NOW()),
  (gen_random_uuid(), 'Natural Language Processing', 'AI/ML', NOW()),
  (gen_random_uuid(), 'Computer Vision', 'AI/ML', NOW()),
  (gen_random_uuid(), 'Prompt Engineering', 'AI/ML', NOW()),
  (gen_random_uuid(), 'Data Annotation', 'AI/ML', NOW()),
  (gen_random_uuid(), 'AI Evaluation', 'AI/ML', NOW()),
  (gen_random_uuid(), 'Mathematics', 'Mathematics', NOW()),
  (gen_random_uuid(), 'Linear Algebra', 'Mathematics', NOW()),
  (gen_random_uuid(), 'Calculus', 'Mathematics', NOW()),
  (gen_random_uuid(), 'Probability', 'Mathematics', NOW()),
  (gen_random_uuid(), 'Discrete Mathematics', 'Mathematics', NOW()),
  (gen_random_uuid(), 'Business Analysis', 'Business', NOW()),
  (gen_random_uuid(), 'Project Management', 'Business', NOW()),
  (gen_random_uuid(), 'Marketing', 'Business', NOW()),
  (gen_random_uuid(), 'Operations', 'Business', NOW()),
  (gen_random_uuid(), 'Supply Chain', 'Business', NOW()),
  (gen_random_uuid(), 'Product Management', 'Business', NOW()),
  (gen_random_uuid(), 'Financial Analysis', 'Finance', NOW()),
  (gen_random_uuid(), 'Accounting', 'Finance', NOW()),
  (gen_random_uuid(), 'Valuation', 'Finance', NOW()),
  (gen_random_uuid(), 'Financial Modeling', 'Finance', NOW()),
  (gen_random_uuid(), 'English', 'Language', NOW()),
  (gen_random_uuid(), 'French', 'Language', NOW()),
  (gen_random_uuid(), 'Spanish', 'Language', NOW()),
  (gen_random_uuid(), 'German', 'Language', NOW()),
  (gen_random_uuid(), 'Portuguese', 'Language', NOW()),
  (gen_random_uuid(), 'Mandarin', 'Language', NOW()),
  (gen_random_uuid(), 'Arabic', 'Language', NOW()),
  (gen_random_uuid(), 'Swahili', 'Language', NOW()),
  (gen_random_uuid(), 'Translation', 'Language', NOW()),
  (gen_random_uuid(), 'Technical Writing', 'Writing', NOW()),
  (gen_random_uuid(), 'Research', 'Writing', NOW()),
  (gen_random_uuid(), 'Editing', 'Writing', NOW()),
  (gen_random_uuid(), 'Fact Checking', 'Writing', NOW()),
  (gen_random_uuid(), 'Problem Solving', 'General', NOW()),
  (gen_random_uuid(), 'Critical Thinking', 'General', NOW()),
  (gen_random_uuid(), 'Attention to Detail', 'General', NOW());